#!/usr/bin/env php
<?php

unset($argv[0]);
$argv = array_values($argv);

$mOutput = NULL;
switch ($argv[0]) {
    case 'run':

        if (isset($argv[1]) && $argv[1] == 'as-service') {
            exec('nohup php ' . __DIR__ . '/src/app.php &', $output);
        } else if (isset($argv[1]) && strpos($argv[1], 'interpreter') !== false) {
			$interpreter = explode('=', $argv[1]);
			
			if (isset($interpreter[1])) {
				exec($interpreter[1] . ' ' . __DIR__ . '/src/app.php', $output);
			} else {
				$mOutput = '-> Where is the interpreter path';
			}
			
			
		} else {
            exec('php ' . __DIR__ . '/src/app.php', $output);
        }


        if (!empty($output)) {
            $exit = NULL;
            foreach($output as $line) {
                $exit .= $line . "\n";
            }

            $mOutput = '-> ' . $exit;
        }

        break;

    case 'create-program':
        if (isset($argv[1])) {
            exec('php ' . __DIR__ . '/scripts/create-program.php ' . $argv[1], $output);

            if (!empty($output)) {
                $exit = NULL;
                foreach($output as $line) {
                    $exit .= $line . "\n";
                }

                $mOutput = '-> ' . $exit;
            }

        } else {
            $mOutput = "-> Where the program name?\n";
        }

        break;

    case 'include-program':
            if (isset($argv[1])) {
                exec('php ' . __DIR__ . '/scripts/include-program.php ' . $argv[1], $output);

                if (!empty($output)) {
                    $exit = NULL;
                    foreach($output as $line) {
                        $exit .= $line . "\n";
                    }

                    $mOutput = '-> ' . $exit;
                }

            } else {
                $mOutput = "-> Where the program name?\n";
            }

            break;

    default:
        $mOutput = "-> Commando not found\n";
        break;

}

exit($mOutput);